### ISSUE TITLE
Semi-minimal reproduction

### ISSUE THREAD

**Issue by thecrypticace** [alin23/m1-panic#2]
This is a minimized-ish version of this reproduction. It still involves node, fish, and entr but in as minimal way as possible. The active task at the time of the panic appears to be node.

Weirdly enough this does NOT panic in an **interactive fish shell**.

test.sh:
```shell
#!/opt/homebrew/bin/fish

node ./test.js &
echo temp.css | entr -s 'echo "New files"'
```

test.js:
```js
process.stdin.resume();
```

temp.css:
```css
/** can be literally anything */
```

Reproduce the panic:
```
chmod +x ./test.sh
./test.sh
```

**Comment by alin23** [comment]
I knew it has nothing to do with Tailwind, but that's the only way I was able to reproduce it at the time 😅

Thanks for the much simpler version! I'll test it and replace what I currently have with your version
